export interface CompanySeed {
  name: string;
  tagline: string;
  markets: string[];
  tech: string[];
  serves: string[];
  investors: string[];
  competesWith: string[];
  partnersWith: string[];
}

export const markets: { name: string; blurb: string }[] = [
  {
    name: "AI Coding Assistants",
    blurb: "AI pair programmers and code generation tools",
  },
  { name: "Foundation Models", blurb: "Frontier LLM research and model APIs" },
  {
    name: "AI Infrastructure",
    blurb: "Tooling and platforms for building AI applications",
  },
  {
    name: "AI Search",
    blurb: "LLM-powered answer engines and retrieval products",
  },
  { name: "Payments Infrastructure", blurb: "APIs for moving money online" },
  {
    name: "Spend Management",
    blurb: "Corporate cards, expenses, and procurement",
  },
  { name: "Business Banking", blurb: "Banking products for startups and SMBs" },
  { name: "Design Tools", blurb: "Interface design and prototyping software" },
  {
    name: "Project Management",
    blurb: "Issue tracking and product planning tools",
  },
  {
    name: "Internal Tools",
    blurb: "Low-code builders for operational software",
  },
  {
    name: "Cloud Platforms",
    blurb: "Hosting, deployment, and developer clouds",
  },
  {
    name: "Data Infrastructure",
    blurb: "Databases, warehouses, and observability",
  },
  {
    name: "Productivity Software",
    blurb: "Docs, knowledge, and team communication",
  },
  {
    name: "Workflow Automation",
    blurb: "Connecting apps and automating business processes",
  },
];

export const segments: string[] = [
  "Software Developers",
  "Startups",
  "Enterprises",
  "Designers",
  "Finance Teams",
  "Product Teams",
  "Data Teams",
  "SMBs",
];

export const technologies: string[] = [
  "Large Language Models",
  "Vector Search",
  "RAG Pipelines",
  "GPU Compute",
  "React",
  "Next.js",
  "TypeScript",
  "PostgreSQL",
  "Kubernetes",
  "Rust",
  "CRDTs",
  "WebAssembly",
  "WebRTC",
];

export const investors: string[] = [
  "Sequoia Capital",
  "Andreessen Horowitz",
  "Y Combinator",
  "Thrive Capital",
  "Index Ventures",
  "Benchmark",
  "Accel",
  "Founders Fund",
  "General Catalyst",
  "Khosla Ventures",
];

export const companies: CompanySeed[] = [
  {
    name: "Cursor",
    tagline: "AI-first code editor",
    markets: ["AI Coding Assistants"],
    tech: ["Large Language Models", "RAG Pipelines", "TypeScript"],
    serves: ["Software Developers", "Enterprises"],
    investors: ["Thrive Capital", "Andreessen Horowitz"],
    competesWith: ["Windsurf", "GitHub", "Replit"],
    partnersWith: ["Anthropic", "OpenAI"],
  },
  {
    name: "Windsurf",
    tagline: "Agentic AI development environment",
    markets: ["AI Coding Assistants"],
    tech: ["Large Language Models", "RAG Pipelines"],
    serves: ["Software Developers", "Enterprises"],
    investors: ["General Catalyst", "Founders Fund"],
    competesWith: ["Cursor", "GitHub", "Replit"],
    partnersWith: [],
  },
  {
    name: "Replit",
    tagline: "AI-powered cloud development platform",
    markets: ["AI Coding Assistants", "Cloud Platforms"],
    tech: ["Large Language Models", "Kubernetes", "TypeScript"],
    serves: ["Software Developers", "Startups"],
    investors: ["Andreessen Horowitz", "Y Combinator", "Khosla Ventures"],
    competesWith: ["Cursor", "Windsurf", "Vercel"],
    partnersWith: ["Anthropic"],
  },
  {
    name: "GitHub",
    tagline: "Developer platform and AI pair programmer",
    markets: ["AI Coding Assistants", "Project Management"],
    tech: ["Large Language Models", "TypeScript", "Kubernetes"],
    serves: ["Software Developers", "Enterprises"],
    investors: ["Sequoia Capital", "Andreessen Horowitz"],
    competesWith: ["Cursor", "Windsurf", "Linear"],
    partnersWith: ["OpenAI"],
  },
  {
    name: "OpenAI",
    tagline: "Frontier AI research and APIs",
    markets: ["Foundation Models", "AI Search"],
    tech: ["Large Language Models", "GPU Compute", "RAG Pipelines"],
    serves: ["Software Developers", "Enterprises", "Startups"],
    investors: ["Thrive Capital", "Khosla Ventures", "Sequoia Capital"],
    competesWith: ["Anthropic", "Mistral AI", "Perplexity"],
    partnersWith: ["GitHub", "Stripe", "Zapier"],
  },
  {
    name: "Anthropic",
    tagline: "AI safety and Claude models",
    markets: ["Foundation Models"],
    tech: ["Large Language Models", "GPU Compute", "Rust"],
    serves: ["Software Developers", "Enterprises", "Startups"],
    investors: ["Founders Fund", "General Catalyst"],
    competesWith: ["OpenAI", "Mistral AI"],
    partnersWith: ["Notion", "Slack", "Cursor", "Replit"],
  },
  {
    name: "Mistral AI",
    tagline: "Open-weight frontier models",
    markets: ["Foundation Models"],
    tech: ["Large Language Models", "GPU Compute"],
    serves: ["Software Developers", "Enterprises"],
    investors: ["Andreessen Horowitz", "Index Ventures", "General Catalyst"],
    competesWith: ["OpenAI", "Anthropic"],
    partnersWith: ["Hugging Face"],
  },
  {
    name: "Perplexity",
    tagline: "AI answer engine",
    markets: ["AI Search"],
    tech: ["Large Language Models", "RAG Pipelines", "Vector Search"],
    serves: ["Startups", "Enterprises"],
    investors: ["Y Combinator", "Andreessen Horowitz"],
    competesWith: ["OpenAI"],
    partnersWith: [],
  },
  {
    name: "Hugging Face",
    tagline: "The home of open machine learning",
    markets: ["AI Infrastructure", "Foundation Models"],
    tech: ["Large Language Models", "Vector Search", "Kubernetes"],
    serves: ["Software Developers", "Data Teams"],
    investors: ["Sequoia Capital", "Andreessen Horowitz"],
    competesWith: ["OpenAI"],
    partnersWith: ["Databricks", "Mistral AI"],
  },
  {
    name: "LangChain",
    tagline: "Framework for LLM applications",
    markets: ["AI Infrastructure"],
    tech: [
      "Large Language Models",
      "RAG Pipelines",
      "Vector Search",
      "TypeScript",
    ],
    serves: ["Software Developers"],
    investors: ["Sequoia Capital", "Benchmark"],
    competesWith: [],
    partnersWith: ["Pinecone", "OpenAI", "Anthropic"],
  },
  {
    name: "Pinecone",
    tagline: "Vector database for AI",
    markets: ["AI Infrastructure", "Data Infrastructure"],
    tech: ["Vector Search", "Kubernetes", "Rust"],
    serves: ["Software Developers", "Data Teams"],
    investors: ["Andreessen Horowitz", "Index Ventures"],
    competesWith: ["Supabase"],
    partnersWith: ["LangChain", "Vercel"],
  },
  {
    name: "Stripe",
    tagline: "Payments infrastructure for the internet",
    markets: ["Payments Infrastructure", "Business Banking"],
    tech: ["React", "TypeScript", "PostgreSQL"],
    serves: ["Startups", "Enterprises", "SMBs", "Software Developers"],
    investors: ["Sequoia Capital", "General Catalyst", "Founders Fund"],
    competesWith: ["Brex", "Ramp"],
    partnersWith: ["Vercel", "OpenAI", "Ramp"],
  },
  {
    name: "Ramp",
    tagline: "Finance automation and corporate cards",
    markets: ["Spend Management", "Workflow Automation"],
    tech: ["React", "PostgreSQL", "Large Language Models"],
    serves: ["Finance Teams", "Startups", "SMBs"],
    investors: ["Founders Fund", "Thrive Capital"],
    competesWith: ["Brex", "Rippling"],
    partnersWith: ["Stripe"],
  },
  {
    name: "Brex",
    tagline: "Spend platform for scaling companies",
    markets: ["Spend Management", "Business Banking"],
    tech: ["React", "PostgreSQL"],
    serves: ["Finance Teams", "Startups", "Enterprises"],
    investors: ["Y Combinator", "Khosla Ventures"],
    competesWith: ["Ramp", "Mercury", "Stripe"],
    partnersWith: [],
  },
  {
    name: "Mercury",
    tagline: "Banking for startups",
    markets: ["Business Banking"],
    tech: ["React", "PostgreSQL"],
    serves: ["Startups", "SMBs", "Finance Teams"],
    investors: ["Andreessen Horowitz", "Y Combinator"],
    competesWith: ["Brex"],
    partnersWith: ["Stripe"],
  },
  {
    name: "Vercel",
    tagline: "Frontend cloud and AI deployment",
    markets: ["Cloud Platforms"],
    tech: ["Next.js", "React", "TypeScript", "Rust", "Kubernetes"],
    serves: ["Software Developers", "Startups", "Enterprises"],
    investors: ["Accel", "General Catalyst"],
    competesWith: ["Replit"],
    partnersWith: ["Stripe", "OpenAI", "Neon", "Pinecone", "Supabase"],
  },
  {
    name: "Supabase",
    tagline: "Open source Firebase alternative",
    markets: ["Cloud Platforms", "Data Infrastructure"],
    tech: ["PostgreSQL", "TypeScript", "Vector Search"],
    serves: ["Software Developers", "Startups"],
    investors: ["Y Combinator", "Benchmark"],
    competesWith: ["Neon", "Pinecone"],
    partnersWith: ["Vercel"],
  },
  {
    name: "Neon",
    tagline: "Serverless Postgres",
    markets: ["Data Infrastructure"],
    tech: ["PostgreSQL", "Rust", "Kubernetes"],
    serves: ["Software Developers", "Startups"],
    investors: ["General Catalyst", "Khosla Ventures"],
    competesWith: ["Supabase"],
    partnersWith: ["Vercel"],
  },
  {
    name: "Notion",
    tagline: "Connected workspace with AI",
    markets: ["Productivity Software", "Project Management"],
    tech: ["React", "CRDTs", "Large Language Models"],
    serves: ["Product Teams", "Startups", "Enterprises"],
    investors: ["Index Ventures", "Sequoia Capital"],
    competesWith: ["Airtable", "Linear", "Slack"],
    partnersWith: ["Anthropic"],
  },
  {
    name: "Airtable",
    tagline: "No-code apps on a relational base",
    markets: ["Productivity Software", "Internal Tools"],
    tech: ["React", "PostgreSQL"],
    serves: ["Product Teams", "Enterprises", "SMBs"],
    investors: ["Benchmark", "Thrive Capital"],
    competesWith: ["Notion", "Retool"],
    partnersWith: [],
  },
  {
    name: "Linear",
    tagline: "Issue tracking for high-performance teams",
    markets: ["Project Management"],
    tech: ["React", "TypeScript", "CRDTs"],
    serves: ["Product Teams", "Startups", "Software Developers"],
    investors: ["Sequoia Capital", "Accel"],
    competesWith: ["Notion", "GitHub"],
    partnersWith: ["Figma", "Slack", "GitHub"],
  },
  {
    name: "Figma",
    tagline: "Collaborative interface design",
    markets: ["Design Tools"],
    tech: ["React", "CRDTs", "WebAssembly"],
    serves: ["Designers", "Product Teams", "Enterprises"],
    investors: ["Index Ventures", "Sequoia Capital", "Thrive Capital"],
    competesWith: ["Framer"],
    partnersWith: ["Linear", "Slack"],
  },
  {
    name: "Framer",
    tagline: "AI-powered site design and publishing",
    markets: ["Design Tools"],
    tech: ["React", "TypeScript", "Large Language Models"],
    serves: ["Designers", "Startups"],
    investors: ["Accel", "Index Ventures"],
    competesWith: ["Figma"],
    partnersWith: [],
  },
  {
    name: "Retool",
    tagline: "Build internal tools fast",
    markets: ["Internal Tools"],
    tech: ["React", "PostgreSQL", "TypeScript"],
    serves: ["Software Developers", "Enterprises", "Finance Teams"],
    investors: ["Sequoia Capital", "Y Combinator"],
    competesWith: ["Airtable", "Zapier"],
    partnersWith: ["Snowflake", "Datadog"],
  },
  {
    name: "Zapier",
    tagline: "Automation for busy people",
    markets: ["Workflow Automation"],
    tech: ["TypeScript", "PostgreSQL", "Large Language Models"],
    serves: ["SMBs", "Product Teams", "Startups"],
    investors: ["Sequoia Capital", "Y Combinator"],
    competesWith: ["Retool", "Airtable"],
    partnersWith: ["Slack", "Notion", "OpenAI"],
  },
  {
    name: "Slack",
    tagline: "Where work happens",
    markets: ["Productivity Software"],
    tech: ["React", "PostgreSQL", "WebRTC"],
    serves: ["Enterprises", "Startups", "Product Teams"],
    investors: ["Accel", "Thrive Capital"],
    competesWith: ["Notion"],
    partnersWith: ["Anthropic", "Linear", "Zapier", "Figma"],
  },
  {
    name: "Datadog",
    tagline: "Monitoring and security for cloud apps",
    markets: ["Data Infrastructure"],
    tech: ["Kubernetes", "Rust", "PostgreSQL"],
    serves: ["Software Developers", "Enterprises", "Data Teams"],
    investors: ["Index Ventures", "Accel"],
    competesWith: [],
    partnersWith: ["Retool"],
  },
  {
    name: "Snowflake",
    tagline: "The AI data cloud",
    markets: ["Data Infrastructure"],
    tech: ["Kubernetes", "GPU Compute"],
    serves: ["Data Teams", "Enterprises"],
    investors: ["Sequoia Capital", "Accel"],
    competesWith: ["Databricks"],
    partnersWith: ["Retool"],
  },
  {
    name: "Databricks",
    tagline: "Unified data and AI platform",
    markets: ["Data Infrastructure", "AI Infrastructure"],
    tech: ["Large Language Models", "Kubernetes", "GPU Compute"],
    serves: ["Data Teams", "Enterprises"],
    investors: ["Andreessen Horowitz", "Thrive Capital"],
    competesWith: ["Snowflake"],
    partnersWith: ["Hugging Face"],
  },
  {
    name: "Rippling",
    tagline: "HR, IT, and finance in one platform",
    markets: ["Spend Management", "Workflow Automation"],
    tech: ["React", "PostgreSQL"],
    serves: ["Finance Teams", "SMBs", "Enterprises"],
    investors: ["Founders Fund", "Sequoia Capital", "Y Combinator"],
    competesWith: ["Ramp", "Brex"],
    partnersWith: [],
  },
];
